services:
  code:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: experiments-code
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
